# Generated by Django 2.1b1 on 2018-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
